# -*- coding: utf-8 -*-
"""POC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3RR2f2o8fc-T4tyWSBWIzVi6yfc6ST5
"""

#!pip install Streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Create dummy data
data = {
    'Category': ['A', 'B', 'C', 'D'],
    'Values': [23, 45, 56, 78]
}
df = pd.DataFrame(data)

# Streamlit application
st.title('Simple Bar Chart with Dummy Data')

st.write('This is a simple bar chart using dummy data.')

# Plotting the bar chart
fig, ax = plt.subplots()
ax.bar(df['Category'], df['Values'])
ax.set_xlabel('Category')
ax.set_ylabel('Values')
ax.set_title('Bar Chart')

st.pyplot(fig)